name: CI

on:
  push:
    branches:
      - main
      - master
      - beta

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Node.js version to install from `.nvmrc`
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Install required Node.js version
        uses: actions/setup-node@v1
        with:
          cache: 'pnpm'
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: PNPM install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm turbo run build lint

      - name: Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta')
        run: pnpm semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
